### ISSUE TITLE
TypeError: Cannot read property 'location' of undefined

### ISSUE THREAD

**Issue by derekhassan** [Danielson9712/dissidia-reloaded-website#1]
Website will not load, seems to be an issue with the import of react router. 
![image](https://user-images.githubusercontent.com/26441727/118056640-4caf8f80-b358-11eb-9891-6dd819e56c54.png)

Should be as below:
`import { BrowserRouter as Router, Route} from 'react-router-dom';`

**Comment by Danielson9712** [comment]
Hmm ok thank you I will look into this issue. So sorry this site is giving you errors!
